definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
      isSucces:
        type: boolean
      message:
        type: string
    type: object
  dto.RegisterReq:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    type: object
  dto.RegisterRes:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
    type: object
  dto.Response-dto_RegisterRes:
    properties:
      data:
        $ref: '#/definitions/dto.RegisterRes'
      isSucces:
        type: boolean
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/register:
    post:
      consumes:
      - application/json
      description: Create a new user account with email and password
      parameters:
      - description: Registration Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterReq'
      produces:
      - application/json
      responses:
        "201":
          description: Registration successful
          schema:
            $ref: '#/definitions/dto.Response-dto_RegisterRes'
        "400":
          description: Invalid input validation
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Email already registered
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Register a new user
      tags:
      - Authentication
swagger: "2.0"
